spring.application.name=aerienne

# PostgreSQL datasource
# Remplacez les valeurs 'username' et 'password' par vos identifiants locaux
spring.datasource.url=jdbc:postgresql://localhost:5432/aerienne
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate (optionnel — ajustez selon vos besoins)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Serveur web
server.port=8080